pre-run:
  - echo 'hello command'
  - script: console.log('hello script')
  - |
    echo 'hello'
    echo 'multi-line command'
  - script: |
      console.log('hello')
      console.log('multi-line script')
